services:
  hotech_room:
    build: .
    container_name: room_container
    image: hotech_room
    ports:
      - "8005:8005"
    #environment:
    #  DB_URL: jdbc:mysql://room_db:3306/hotech_backend?createDatabaseIfNotExist=true&serverTimezone=UTC
    #  DB_USERNAME: root
    #  DB_PASSWORD: securepassword123
    restart: on-failure
    depends_on:
      - room_db
    networks:
      - red-microservices

  room_db:
    container_name: room_db
    image: 'mysql:latest'
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
    networks:
      - red-microservices

networks:
  red-microservices:
    external: true