version: '3'
services:
  #---------------------MESSAGE BROKER--------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - red-microservices

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    restart: on-failure
    networks:
      - red-microservices
      
  #------------------DATABASES----------------------------
  profile_db:
    container_name: profile_db
    image: 'mysql:latest'
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
    networks:
      - red-microservices

  message_db:
    container_name: message_db
    image: 'mysql:latest'
    ports:
      - "3303:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
    networks:
      - red-microservices

  inventory_db:
    container_name: inventory_db
    image: 'mysql:latest'
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
    networks:
      - red-microservices

  room_db:
    container_name: room_db
    image: 'mysql:latest'
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: securepassword123
      MYSQL_PASSWORD: securepassword123
      MYSQL_DATABASE: hotech_backend
    networks:
      - red-microservices

  #-------------------------MICROSERVICES----------------------------(Los servicios de los microservicios deben tener "-")
  hotech-profile:
    container_name: profile_container
    image: christophermore/hotech_profile
    ports:
      - "8001:8001"
    restart: on-failure
    depends_on:
      - profile_db
    networks:
      - red-microservices

  hotech-message:
    container_name: message_container
    image: christophermore/hotech_message
    ports:
      - "8003:8003"
    restart: on-failure
    depends_on:
      - message_db
    networks:
      - red-microservices

  hotech-inventory:
    container_name: inventory_container
    image: christophermore/hotech_inventory
    ports:
      - "8004:8004"
    restart: on-failure
    depends_on:
      - inventory_db
    networks:
      - red-microservices

  hotech-room:
    container_name: room_container
    image: christophermore/hotech_room
    ports:
      - "8005:8005"
    restart: on-failure
    depends_on:
      - room_db
    networks:
      - red-microservices

  #-------------------------API GATEWAY------------------------------
  hotech-api-gateway:
    container_name: api_gateway_container
    image: christophermore/hotech_api_gateway
    ports:
      - "9101:9101"
    restart: on-failure
    networks:
      - red-microservices

#-----------------------NETWORKS-------------------------------
networks:
  red-microservices:
    external: true